name: Generate Documentation

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the Python version

      # Step 3: Install Docsible from the specified branch
      - name: Install Docsible
        run: |
          pip install git+https://github.com/docsible/docsible.git@name-prefix-in-ansible-lint

      # Step 4: Run Docsible to generate documentation
      - name: Generate documentation for role
        run: |
          docsible -r ./ -g -o README.md -a -com

      # Step 5: Check for changes
      - name: Check for documentation changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --exit-code; then
            echo "No changes to commit";
            exit 0;
          fi

      # Step 6: Commit changes and push to a new branch
      - name: Commit and push changes
        run: |
          # Generate a unique branch name
          branch_name="docs-update-$(date +'%Y%m%d%H%M%S')"
          git checkout -b "$branch_name"
          git commit -m "Automated documentation update by GitHub Actions"
          git push origin "$branch_name"

      # Step 7: Create a pull request
      - name: Create a pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Automated Documentation Update",
              head: "${{ github.actor }}:${{ steps.commit_and_push.outputs.branch_name }}",
              base: "main",
              body: "This pull request contains automated documentation updates generated by GitHub Actions."
            });
            console.log(`Pull request created: ${pullRequest.html_url}`);
